 fly.toml

# Usa il nome corretto della tua app
app = 'zenith-rewards-backend-prod'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

# AGGIUNGI QUESTA SEZIONE ALLA FINE
[processes]
  app = "uvicorn app.main:app --host 0.0.0.0 --port 8080"